name: Analyze code
on:
  workflow_call:
    inputs:
      format:
        type: boolean
        default: true
        required: false
      quality:
        type: boolean
        default: true
        required: false
jobs:
  check_format:
    uses: ./.github/workflows/check_format.yml
    if: ${{ inputs.format == true }}
  check_quality:
    uses: ./.github/workflows/check_quality.yml
    if: ${{ inputs.quality == true }}
