name: Check code quality
on:
  workflow_call:
jobs:
  eslint:
    name: Check code quality
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.5
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 22
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run code analyzer
        run: npm run analyzer:check
