name: Check code format
on:
  workflow_call:
jobs:
  prettier:
    name: Check code format
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.5
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 20
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run code formatter
        run: npm run formatter:check
